### ISSUE TITLE
stuck on "Creating mp3 player task"

### ISSUE THREAD

**Issue by Jefke1** [Brezensalzer/ESP32_Web_Radio#1]
hey,
I built your project, I have a problem with entering the radio stations.
It gets stuck on "Creating mp3 player task"
How can I add these stations?
http://icecast-qmusic.cdp.triple-it.nl/JOEfm_be_live_128.mp3
http://icecast.vrtcdn.be/stubru_tijdloze-high.mp3
Thanks in advance.

**Comment by Brezensalzer** [comment]
Hello,

sorry for my late reply!
A line in stationlist.txt looks like
`<Station Name>;<hostname>;<path>;<tcp-port>`

that would be in Your example:
Station_1;icecast-qmusic.cdp.triple-it.nl;/JOEfm_be_live_128.mp3;80
Station_2;icecast.vrtcdn.be;/stubru_tijdloze-high.mp3;80
